language: node_js
node_js:
  - node
cache: npm

services:
  - docker

install:
  - npm i

script:
  - npm run -s lint
  - >
    if [[ $TRAVIS_EVENT_TYPE != 'pull_request' ||  $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then
      if [[ $TRAVIS_BRANCH != 'master' ]]; then
        npm run chromatic
      else
        # see http://docs.chromaticqa.com/setup_ci#maintain-a-clean-master-branch
        npm run chromatic --auto-accept-changes
      fi
    fi

before_deploy:
  - echo $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin
  - export IMAGE_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "dev"; fi`
  - export IMAGE_NAME="piterpy/postpost-frontend"
  - docker build -t $IMAGE_NAME:$IMAGE_TAG .

deploy:
  provider: script
  script: docker push $IMAGE_NAME:$IMAGE_TAG
  on:
    condition: $TRAVIS_BRANCH =~ ^master|develop$
    all_branches: true
